/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alchemist

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'alchemist.greeting' plugin.
 */
class AlchemistPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.yonatankarp.alchemist")

        // Verify the result
        assertNotNull(project.tasks.findByName("generateOpenApiSpecs"))
    }
}
